### ISSUE TITLE
Drilldown example?

### ISSUE THREAD

**Issue by victorhooi** [jhuenges/highcharts-demo#2]
It'd be awesome to include a drilldown demo as well, using this plugin =)!

**Comment by jhuenges** [comment]
I ll see what I can do :)

**Comment by jhuenges** [comment]
[Here](https://github.com/jhuenges/highcharts-demo/blob/master/client/demos/drillDownDemo.html) [you](https://github.com/jhuenges/highcharts-demo/blob/master/client/demos/drillDownDemo.js) [go](http://highcharts-demo.meteor.com/)
